import { Component, OnInit, EventEmitter, Output } from '@angular/core';
import { ActionsTypes, ActionEvent } from '../../state/state';

@Component({
  selector: 'app-navbarindexlafd',
  templateUrl: './navbarindexlafd.component.html',
  styleUrls: ['./navbarindexlafd.component.css']
})
export class NavbarindexlafdComponent implements OnInit {
  alphabet=[
    {"idabjd": 1,
    "nharf": "ألف",
    "harf": "ا",
    "type": "سامي"},
    {"idabjd": 2,
    "nharf": "باء",
    "harf": "ب",
    "type": "سامي"},
    {"idabjd": 22,
    "nharf": "تاء",
    "harf": "ت",
    "type": "سامي"},
    { "idabjd": 23,
    "nharf": "ثاء",
    "harf": "ث",
    "type": "عربي"},
    {"idabjd": 3,
    "nharf": "جيم",
    "harf": "ج",
    "type": "سامي"},
  {"idabjd": 8,
  "nharf": "حاء",
  "harf": "ح",
  "type": "سامي"},
  {"idabjd": 24,
  "nharf": "خاء",
  "harf": "خ",
  "type": "عربي"},
  { "idabjd": 4,
  "nharf": "دال",
  "harf": "د",
  "type": "سامي"},
  {"idabjd": 25,
  "nharf": "ذال",
  "harf": "ذ",
  "type": "عربي"},
  {"idabjd": 20,
  "nharf": "راء",
  "harf": "ر",
  "type": "سامي"},
  {"idabjd": 7,
  "nharf": "زاي",
  "harf": "ز",
  "type": "سامي"},
  {"idabjd": 15,
  "nharf": "سين",
  "harf": "س",
  "type": "سامي"},
  {"idabjd": 21,
  "nharf": "شين",
  "harf": "ش",
  "type": "سامي"},
  {"idabjd": 18,
  "nharf": "صاد",
  "harf": "ص",
  "type": "سامي"},
  {"idabjd": 26,
  "nharf": "ضاد",
  "harf": "ض",
  "type": "عربي"},
  {"idabjd": 9,
  "nharf": "طاء",
  "harf": "ط",
  "type": "سامي"},
  { "idabjd": 27,
  "nharf": "ظاء",
  "harf": "ظ",
  "type": "عربي"},
  {"idabjd": 16,
  "nharf": "عين",
  "harf": "ع",
  "type": "سامي"},
  {"idabjd": 28,
  "nharf": "غين",
  "harf": "غ",
  "type": "عربي"},
  {"idabjd": 17,
  "nharf": "فاء",
  "harf": "ف",
  "type": "سامي"},
  {"idabjd": 19,
  "nharf": "قاف",
  "harf": "ق",
  "type": "سامي"},
  {"idabjd": 11,
  "nharf": "كاف",
  "harf": "ك",
  "type": "سامي"},
  {"idabjd": 12,
  "nharf": "لام",
  "harf": "ل",
  "type": "سامي"},
  {"idabjd": 13,
  "nharf": "ميم",
  "harf": "م",
  "type": "سامي"},
  {"idabjd": 14,
  "nharf": "نون",
  "harf": "ن",
  "type": "سامي"},
  {"idabjd": 5,
  "nharf": "هاء",
  "harf": "ه",
  "type": "سامي"},
  {"idabjd": 6,
  "nharf": "واو",
  "harf": "و",
  "type": "سامي"},
  {"idabjd": 10,
  "nharf": "ياء",
  "harf": "ي",
  "type": "سامي"}]


  abjad=[
    {"idabjd": 1,
    "nharf": "الف",
    "harf": "ا",
    "type": "سامي"},
    {"idabjd": 2,
    "nharf": "باء",
    "harf": "ب",
    "type": "سامي"},
    {"idabjd": 3,
    "nharf": "جيم",
    "harf": "ج",
    "type": "سامي"},
    { "idabjd": 4,
    "nharf": "دال",
    "harf": "د",
    "type": "سامي"},
    {"idabjd": 5,
    "nharf": "هاء",
    "harf": "ه",
    "type": "سامي"},
    {"idabjd": 6,
    "nharf": "واو",
    "harf": "و",
    "type": "سامي"},
    {"idabjd": 7,
    "nharf": "زاي",
    "harf": "ز",
    "type": "سامي"},
    {"idabjd": 8,
    "nharf": "حاء",
    "harf": "ح",
    "type": "سامي"},
    {"idabjd": 9,
    "nharf": "طاء",
    "harf": "ط",
    "type": "سامي"},
    {"idabjd": 10,
    "nharf": "ياء",
    "harf": "ي",
    "type": "سامي"},
    {"idabjd": 11,
    "nharf": "كاف",
    "harf": "ك",
    "type": "سامي"},
    {"idabjd": 12,
    "nharf": "لام",
    "harf": "ل",
    "type": "سامي"},
    {"idabjd": 13,
    "nharf": "ميم",
    "harf": "م",
    "type": "سامي"},
    {"idabjd": 14,
    "nharf": "نون",
    "harf": "ن",
    "type": "سامي"},
    {"idabjd": 15,
    "nharf": "سين",
    "harf": "س",
    "type": "سامي"},
    {"idabjd": 16,
    "nharf": "عين",
    "harf": "ع",
    "type": "سامي"},
    {"idabjd": 17,
    "nharf": "فاء",
    "harf": "ف",
    "type": "سامي"},
    {"idabjd": 18,
    "nharf": "صاد",
    "harf": "ص",
    "type": "سامي"},
    {"idabjd": 19,
    "nharf": "قاف",
    "harf": "ق",
    "type": "سامي"},
    {"idabjd": 20,
    "nharf": "راء",
    "harf": "ر",
    "type": "سامي"},
    {"idabjd": 21,
    "nharf": "شين",
    "harf": "ش",
    "type": "سامي"},
        
    {"idabjd": 22,
    "nharf": "تاء",
    "harf": "ت",
    "type": "سامي"},
    { "idabjd": 23,
    "nharf": "ثاء",
    "harf": "ث",
    "type": "عربي"},
    

  {"idabjd": 24,
  "nharf": "خاء",
  "harf": "خ",
  "type": "عربي"},
   {"idabjd": 25,
  "nharf": "ذال",
  "harf": "ذ",
  "type": "عربي"},
   
    {"idabjd": 26,
  "nharf": "ضاد",
  "harf": "ض",
  "type": "عربي"},
    { "idabjd": 27,
  "nharf": "ظاء",
  "harf": "ظ",
  "type": "عربي"},
  
  {"idabjd": 28,
  "nharf": "غين",
  "harf": "غ",
  "type": "عربي"},
  
  
    ]
  @Output() lafdEventEmitter:EventEmitter<ActionEvent> = new EventEmitter();
  constructor() { }

  ngOnInit(): void {
  
  }
  onGetLafdsByHarf() {
    this.lafdEventEmitter.emit({type:ActionsTypes.GET_ALL_LAFDS_BY_HARF})
  }

}
  

